// Package person specifies a set of enumerated values that provides the means for descriptions
// of facts about persons.
// https://github.com/FamilySearch/gedcomx/blob/master/specifications/fact-types-specification.md
package person

import (
	"github.com/yosefda/gedcomx/typedef"
)

// Fact enum type.
type Fact typedef.URI

// Fact is fact that applicable to a person.
// https://github.com/FamilySearch/gedcomx/blob/master/specifications/fact-types-specification.md#21-person-fact-types
const (
	Adoption                  Fact = "http://gedcomx.org/Adoption"
	AdultChristening          Fact = "http://gedcomx.org/AdultChristening"
	Amnesty                   Fact = "http://gedcomx.org/Amnesty"
	AncestralHall             Fact = "http://gedcomx.org/AncestralHall"
	AncestralPoem             Fact = "http://gedcomx.org/AncestralPoem"
	Apprenticeship            Fact = "http://gedcomx.org/Apprenticeship"
	Arrest                    Fact = "http://gedcomx.org/Arrest"
	Award                     Fact = "http://gedcomx.org/Award"
	Baptism                   Fact = "http://gedcomx.org/Baptism"
	BarMitzvah                Fact = "http://gedcomx.org/BarMitzvah"
	BatMitzvah                Fact = "http://gedcomx.org/BatMitzvah"
	Birth                     Fact = "http://gedcomx.org/Birth"
	BirthNotice               Fact = "http://gedcomx.org/BirthNotice"
	Blessing                  Fact = "http://gedcomx.org/Blessing"
	Branch                    Fact = "http://gedcomx.org/Branch"
	Burial                    Fact = "http://gedcomx.org/Burial"
	Caste                     Fact = "http://gedcomx.org/Caste"
	Census                    Fact = "http://gedcomx.org/Census"
	Christening               Fact = "http://gedcomx.org/Christening"
	Circumcision              Fact = "http://gedcomx.org/Circumcision"
	Clan                      Fact = "http://gedcomx.org/Clan"
	Confirmation              Fact = "http://gedcomx.org/Confirmation"
	Court                     Fact = "http://gedcomx.org/Court"
	Cremation                 Fact = "http://gedcomx.org/Cremation"
	Death                     Fact = "http://gedcomx.org/Death"
	Education                 Fact = "http://gedcomx.org/Education"
	EducationEnrollment       Fact = "http://gedcomx.org/EducationEnrollment"
	Emigration                Fact = "http://gedcomx.org/Emigration"
	Enslavement               Fact = "http://gedcomx.org/Enslavement"
	Ethnicity                 Fact = "http://gedcomx.org/Ethnicity"
	Excommunication           Fact = "http://gedcomx.org/Excommunication"
	FirstCommunion            Fact = "http://gedcomx.org/FirstCommunion"
	Funeral                   Fact = "http://gedcomx.org/Funeral"
	GenderChange              Fact = "http://gedcomx.org/GenderChange"
	GenerationNumber          Fact = "http://gedcomx.org/GenerationNumber"
	Graduation                Fact = "http://gedcomx.org/Graduation"
	Heimat                    Fact = "http://gedcomx.org/Heimat"
	Immigration               Fact = "http://gedcomx.org/Immigration"
	Imprisonment              Fact = "http://gedcomx.org/Imprisonment"
	Inquest                   Fact = "http://gedcomx.org/Inquest"
	LandTransaction           Fact = "http://gedcomx.org/LandTransaction"
	Language                  Fact = "http://gedcomx.org/Language"
	Living                    Fact = "http://gedcomx.org/Living"
	MaritalStatus             Fact = "http://gedcomx.org/MaritalStatus"
	Medical                   Fact = "http://gedcomx.org/Medical"
	MilitaryAward             Fact = "http://gedcomx.org/MilitaryAward"
	MilitaryDischarge         Fact = "http://gedcomx.org/MilitaryDischarge"
	MilitaryDraftRegistration Fact = "http://gedcomx.org/MilitaryDraftRegistration"
	MilitaryInduction         Fact = "http://gedcomx.org/MilitaryInduction"
	MilitaryService           Fact = "http://gedcomx.org/MilitaryService"
	Mission                   Fact = "http://gedcomx.org/Mission"
	MoveFrom                  Fact = "http://gedcomx.org/MoveFrom"
	MoveTo                    Fact = "http://gedcomx.org/MoveTo"
	MultipleBirth             Fact = "http://gedcomx.org/MultipleBirth"
	NationalID                Fact = "http://gedcomx.org/NationalId"
	Nationality               Fact = "http://gedcomx.org/Nationality"
	Naturalization            Fact = "http://gedcomx.org/Naturalization"
	NumberOfChildren          Fact = "http://gedcomx.org/NumberOfChildren"
	NumberOfMarriages         Fact = "http://gedcomx.org/NumberOfMarriages"
	Obituary                  Fact = "http://gedcomx.org/Obituary"
	OfficialPosition          Fact = "http://gedcomx.org/OfficialPosition"
	Occupation                Fact = "http://gedcomx.org/Occupation"
	Ordination                Fact = "http://gedcomx.org/Ordination"
	Pardon                    Fact = "http://gedcomx.org/Pardon"
	PhysicalDescription       Fact = "http://gedcomx.org/PhysicalDescription"
	Probate                   Fact = "http://gedcomx.org/Probate"
	Property                  Fact = "http://gedcomx.org/Property"
	Race                      Fact = "http://gedcomx.org/Race"
	Religion                  Fact = "http://gedcomx.org/Religion"
	Residence                 Fact = "http://gedcomx.org/Residence"
	Retirement                Fact = "http://gedcomx.org/Retirement"
	Stillbirth                Fact = "http://gedcomx.org/Stillbirth"
	TaxAssessment             Fact = "http://gedcomx.org/TaxAssessment"
	Tribe                     Fact = "http://gedcomx.org/Tribe"
	Will                      Fact = "http://gedcomx.org/Will"
	Visit                     Fact = "http://gedcomx.org/Visit"
	Yahrzeit                  Fact = "http://gedcomx.org/Yahrzeit"
)
