// Package enum specifies a set of enumerated values that provides the means for descriptions
// of facts about persons.
// https://github.com/FamilySearch/gedcomx/blob/master/specifications/fact-types-specification.md
package enum

import (
	"github.com/yosefda/gedcomx/typedef"
)

// PersonFact enum type.
type PersonFact typedef.URI

// PersonFact are facts that applicable to a person.
// https://github.com/FamilySearch/gedcomx/blob/master/specifications/fact-types-specification.md#21-person-fact-types
const (
	Adoption                  PersonFact = "http://gedcomx.org/Adoption"
	AdultChristening          PersonFact = "http://gedcomx.org/AdultChristening"
	Amnesty                   PersonFact = "http://gedcomx.org/Amnesty"
	AncestralHall             PersonFact = "http://gedcomx.org/AncestralHall"
	AncestralPoem             PersonFact = "http://gedcomx.org/AncestralPoem"
	Apprenticeship            PersonFact = "http://gedcomx.org/Apprenticeship"
	Arrest                    PersonFact = "http://gedcomx.org/Arrest"
	Award                     PersonFact = "http://gedcomx.org/Award"
	Baptism                   PersonFact = "http://gedcomx.org/Baptism"
	BarMitzvah                PersonFact = "http://gedcomx.org/BarMitzvah"
	BatMitzvah                PersonFact = "http://gedcomx.org/BatMitzvah"
	Birth                     PersonFact = "http://gedcomx.org/Birth"
	BirthNotice               PersonFact = "http://gedcomx.org/BirthNotice"
	Blessing                  PersonFact = "http://gedcomx.org/Blessing"
	Branch                    PersonFact = "http://gedcomx.org/Branch"
	Burial                    PersonFact = "http://gedcomx.org/Burial"
	Caste                     PersonFact = "http://gedcomx.org/Caste"
	Census                    PersonFact = "http://gedcomx.org/Census"
	Christening               PersonFact = "http://gedcomx.org/Christening"
	Circumcision              PersonFact = "http://gedcomx.org/Circumcision"
	Clan                      PersonFact = "http://gedcomx.org/Clan"
	Confirmation              PersonFact = "http://gedcomx.org/Confirmation"
	Court                     PersonFact = "http://gedcomx.org/Court"
	Cremation                 PersonFact = "http://gedcomx.org/Cremation"
	Death                     PersonFact = "http://gedcomx.org/Death"
	Education                 PersonFact = "http://gedcomx.org/Education"
	EducationEnrollment       PersonFact = "http://gedcomx.org/EducationEnrollment"
	Emigration                PersonFact = "http://gedcomx.org/Emigration"
	Enslavement               PersonFact = "http://gedcomx.org/Enslavement"
	Ethnicity                 PersonFact = "http://gedcomx.org/Ethnicity"
	Excommunication           PersonFact = "http://gedcomx.org/Excommunication"
	FirstCommunion            PersonFact = "http://gedcomx.org/FirstCommunion"
	Funeral                   PersonFact = "http://gedcomx.org/Funeral"
	GenderChange              PersonFact = "http://gedcomx.org/GenderChange"
	GenerationNumber          PersonFact = "http://gedcomx.org/GenerationNumber"
	Graduation                PersonFact = "http://gedcomx.org/Graduation"
	Heimat                    PersonFact = "http://gedcomx.org/Heimat"
	Immigration               PersonFact = "http://gedcomx.org/Immigration"
	Imprisonment              PersonFact = "http://gedcomx.org/Imprisonment"
	Inquest                   PersonFact = "http://gedcomx.org/Inquest"
	LandTransaction           PersonFact = "http://gedcomx.org/LandTransaction"
	Language                  PersonFact = "http://gedcomx.org/Language"
	Living                    PersonFact = "http://gedcomx.org/Living"
	MaritalStatus             PersonFact = "http://gedcomx.org/MaritalStatus"
	Medical                   PersonFact = "http://gedcomx.org/Medical"
	MilitaryAward             PersonFact = "http://gedcomx.org/MilitaryAward"
	MilitaryDischarge         PersonFact = "http://gedcomx.org/MilitaryDischarge"
	MilitaryDraftRegistration PersonFact = "http://gedcomx.org/MilitaryDraftRegistration"
	MilitaryInduction         PersonFact = "http://gedcomx.org/MilitaryInduction"
	MilitaryService           PersonFact = "http://gedcomx.org/MilitaryService"
	Mission                   PersonFact = "http://gedcomx.org/Mission"
	MoveFrom                  PersonFact = "http://gedcomx.org/MoveFrom"
	MoveTo                    PersonFact = "http://gedcomx.org/MoveTo"
	MultipleBirth             PersonFact = "http://gedcomx.org/MultipleBirth"
	NationalID                PersonFact = "http://gedcomx.org/NationalId"
	Nationality               PersonFact = "http://gedcomx.org/Nationality"
	Naturalization            PersonFact = "http://gedcomx.org/Naturalization"
	NumberOfChildren          PersonFact = "http://gedcomx.org/NumberOfChildren"
	NumberOfMarriages         PersonFact = "http://gedcomx.org/NumberOfMarriages"
	Obituary                  PersonFact = "http://gedcomx.org/Obituary"
	OfficialPosition          PersonFact = "http://gedcomx.org/OfficialPosition"
	Occupation                PersonFact = "http://gedcomx.org/Occupation"
	Ordination                PersonFact = "http://gedcomx.org/Ordination"
	Pardon                    PersonFact = "http://gedcomx.org/Pardon"
	PhysicalDescription       PersonFact = "http://gedcomx.org/PhysicalDescription"
	Probate                   PersonFact = "http://gedcomx.org/Probate"
	Property                  PersonFact = "http://gedcomx.org/Property"
	Race                      PersonFact = "http://gedcomx.org/Race"
	Religion                  PersonFact = "http://gedcomx.org/Religion"
	Residence                 PersonFact = "http://gedcomx.org/Residence"
	Retirement                PersonFact = "http://gedcomx.org/Retirement"
	Stillbirth                PersonFact = "http://gedcomx.org/Stillbirth"
	TaxAssessment             PersonFact = "http://gedcomx.org/TaxAssessment"
	Tribe                     PersonFact = "http://gedcomx.org/Tribe"
	Will                      PersonFact = "http://gedcomx.org/Will"
	Visit                     PersonFact = "http://gedcomx.org/Visit"
	Yahrzeit                  PersonFact = "http://gedcomx.org/Yahrzeit"
)
